### ISSUE TITLE
Eraser functionality 

### ISSUE THREAD

**Issue by ramaranjandey** [EPNW/painter#1]
how to erase like an physical eraser on the canvas

**Comment by EP-u-NW** [comment]
There is no build in function for that, only an undo function.
You can make an eraser yourselfe if you provide an erase button that sets the foreground color to the background color :)

**Comment by ramaranjandey** [comment]
yes thanks for your response ...................... i got the idea of doing
it ... and done with the functionality ..... but not like what u said ....i
am not doing it like make the foreground color same as background ....but i
am doing something permanent.

**Comment by DineshkumarThiran** [comment]
How to change the default drawing colour of (Black) into some other colour

**Comment by pkacprzak** [comment]
> There is no build in function for that, only an undo function.
> You can make an eraser yourselfe if you provide an erase button that sets the foreground color to the background color :)

That's sufficient if one is drawing on a solid background, however, I'd we great to have a proper eraser functionality, so for instance, it works when one is drawing over an image background. Any plans to implement this?

**Comment by tmarzeion** [comment]
I've added support for erase mode. Note that it works only on transparent background color.
https://github.com/tmarzeion/painter/commit/d2ce37f8103abd7f1e34c54f78768c87a121ee88
Simply set PainterController's eraseMode property to true.

**Comment by EP-u-NW** [comment]
Hi,
I already peaked at your code. If you would open a PR, Update the LICENSE file to add your name, and briefly explain in the PR how the erease mode works I would merge it :)

**Comment by tmarzeion** [comment]
@EPNW 
https://github.com/EPNW/painter/pull/18
Sorry for not supporting colored background, but I don't have enough time to implement that ATM.

**Comment by EP-u-NW** [comment]
This is finally implemented, seed #18 and 62514755d7f72cb2aaeb74a887338b75f427f589
