### ISSUE TITLE
Cant find where the picture is exported?

### ISSUE THREAD

**Issue by trueshail** [EPNW/painter#11]
Cant find the feature export to png on a device

**Comment by EP-u-NW** [comment]
The picture is not exported as file, you can just get ist bytes or as dart:ui Image, see the the [Picture Controller.finish](https://pub.dev/documentation/painter/latest/painter/PainterController/finish.html) to get an instance of [PictureDetails](https://pub.dev/documentation/painter/latest/painter/PictureDetails-class.html).
