### ISSUE TITLE
Suggestion : make getter method about _pathHistory in PaintController class.

### ISSUE THREAD

**Issue by rbtlr90** [EPNW/painter#13]
I've tried to use this package in my app, and I think getter method about _pathHistory could be useful.
I used the package as sign pad, and I need a state of _path in the pathHistory class to get an information about sign pad's state whether sign pad is null or not.
So I added a few code in the PainterController class and _PathHistory class, like this :
 in _PathHistory,
`List<MapEntry<Path,Paint>> get paths => _paths;`

in PainterController.
`  _PathHistory get pathHistory => _pathHistory; `

This short codes enables me to make stop when there's no signature on the sign pad.
But it's uncomfortable to add this codes whenever I made new projects, so I suggest you to add this codes to original.

**Comment by EP-u-NW** [comment]
Interesting proposal. Do you really need the path history or just if something was drawn? If yes, this could be the same as the first point of #9. I'm closing this issue but feel free to reopen it if thats not what you need.
