### ISSUE TITLE
Bug: Color does not refresh on ColorPickerArea

### ISSUE THREAD

**Issue by songyiYu** [EPNW/painter#14]
I've tested on Emulator Nexus 5x API 27.

I found that ColorPickerArea does not change if I select color on ColorPickerSlider.

<img width="403" alt="스크린샷 2019-10-18 오후 6 35 32" src="https://user-images.githubusercontent.com/9947963/67083430-1e96b780-f1d6-11e9-99ea-663a91cbe2c8.png">

But it works well on iOS simulator.

**Comment by EP-u-NW** [comment]
The color picker is an external dependency and not maintained by us. You can read more about it at https://pub.dev/packages/flutter_colorpicker
