### ISSUE TITLE
[URGENT] making changes

### ISSUE THREAD

**Issue by fxyong** [EPNW/painter#20]
Is is possible to make changes to the drawing stroke (eg: add new stroke, erase some stroke) after i am done with the drawing. For instance, i am done with the current drawing (in drawing screen), i navigate back to the home screen and i select the same drawing again to bring me back to the drawing screen, am i able to erase previously drawn stroke?

**Comment by tmarzeion** [comment]
Actually I've implemented similar logic in my app, take a look.
https://github.com/tmarzeion/flutter-drawable-notepad/blob/35108caaef1160c77a7681e255877ea9d060d117/lib/routes/note/note_route.dart#L268
To achieve that, I've used my modified version of this painter lib:
https://github.com/tmarzeion/flutter-drawable-notepad/blob/35108caaef1160c77a7681e255877ea9d060d117/pubspec.yaml#L46
