### ISSUE TITLE
Multi touch bug

### ISSUE THREAD

**Issue by RenanDelfanti** [EPNW/painter#21]
When I click with two fingers, I have a line draw.
It's possible to disable a multi touch functionality?

**Comment by tmarzeion** [comment]
It is possible, but library has to be slightly modified to block touch events if there is another touch event in progress already.
https://github.com/EPNW/painter/blob/1a9e5d5a491c77fd42a87c2f3221d8122eebd6f1/lib/painter.dart#L46
