### ISSUE TITLE
Erase Mode Error Flutter Web

### ISSUE THREAD

**Issue by rupamking1** [EPNW/painter#26]
I got a error when I try to Erase lines please fix it.

<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/97000301-3674ea00-1554-11eb-8af6-1813de3766ae.png">

**Comment by EP-u-NW** [comment]
Hm thats a very interesting error, but it seems that it's releated to flutter. I'll try to reproduce and comment later.

**Comment by EP-u-NW** [comment]
Ok, so it seems flutter fixed this.
