### ISSUE TITLE
Support - Adding New custom shape using Custom paint on canvas.

### ISSUE THREAD

**Issue by anujraghuvanshi** [EPNW/painter#30]
Guys, is there any way we can add our custom drawing shape to cavas ??

Or any way we can get instance of canvas which can help to get painted over it ? Just like any circle on canvas as shown in image.

![image](https://user-images.githubusercontent.com/22232709/116995033-2bff8e00-acf7-11eb-9993-28b7f60e7adc.png)

**Comment by EP-u-NW** [comment]
This is currently no possible nor planed. You can fork this repo and implement this by yourselfe.
