### ISSUE TITLE
How can I store the location of a path as a list of offsets?

### ISSUE THREAD

**Issue by PeterTF656** [EPNW/painter#35]
I would like to save the drawing as a list of lists. More specifically, a list of paths that each has a list of offset points in (x and y). Is this possible using the PainterController in this package?

**Comment by EP-u-NW** [comment]
Not out of the box, but I'm sure you could work something out to fit your needs. Maybe if you look at the `_PathHistory` class here
https://github.com/EPNW/painter/blob/ac1555d1bab8dd1afb0976d97bc9dcb78f527e93/lib/painter.dart#L99
and make it public, as well as making the respective property of the `PainterController` public here
https://github.com/EPNW/painter/blob/ac1555d1bab8dd1afb0976d97bc9dcb78f527e93/lib/painter.dart#L204
you could access the information you need.

**Comment by PeterTF656** [comment]
> Not out of the box, but I'm sure you could work something out to fit your needs. Maybe if you look at the `_PathHistory` class here
> https://github.com/EPNW/painter/blob/ac1555d1bab8dd1afb0976d97bc9dcb78f527e93/lib/painter.dart#L99
> 
> 
> and make it public, as well as making the respective property of the `PainterController` public here
> https://github.com/EPNW/painter/blob/ac1555d1bab8dd1afb0976d97bc9dcb78f527e93/lib/painter.dart#L204
> 
> 
> you could access the information you need.

Thank you! I have figured it out!
