### ISSUE TITLE
Method of further modifying a picture after it has been finished

### ISSUE THREAD

**Issue by MichaelFerrier** [EPNW/painter#4]
When finish() is called on the PaintController for the first time, a Picture is rendered from the paths. Any later calls to finish() will return that same Picture, which was cached by the first call to finish(). So, any changes made (such as new paths added) after the first call to finish() will be left out of the output Picture.

It would be very useful to be able to make changes, output the Picture (for example to save to disk as a bitmap), then be able to make further changes and output the picture again, with these new changes.

As far as I can tell there's currently no way to do this? If that's the case, it would be a very welcome addition. Thank you!

**Comment by EP-u-NW** [comment]
Hi, this feature seems to be the same as requested in #9, so I'm closing this here now.
