### ISSUE TITLE
access to image data while it is not finished

### ISSUE THREAD

**Issue by gbuela** [EPNW/painter#9]
before I set the painter as finished I would like to:
- know if anything has been painted at all (true/false)
- get a snapshot image of the drawing but still let the user draw more
is that possible?

**Comment by EP-u-NW** [comment]
The first part of your request is now implemented, see [PainterController.isEmpty](https://pub.dev/documentation/painter/latest/painter/PainterController/isEmpty.html).

There are currently no plans to impelent the second part, but feel free to open a pr :)

**Comment by tmarzeion** [comment]
I've implemented painting history serialization/deserialization mechanism for my app purposes.
Unfortunately my painter fork is modified too much to make PR out of it.
Maybe you or @EPNW could grab some inspiration out of this code and implement it here :)
https://github.com/tmarzeion/painter/blob/master/lib/painter.dart
`String get history {
    return _serializeHistory();
  }`

**Comment by EP-u-NW** [comment]
@tmarzeion I gave you direct access to this repo :) I've you want to integrate your code, feel free to open a new branch, test it there and open a pr once you are ready.

**Comment by tmarzeion** [comment]
Sure, I will try to integrate that when I find some time :)
I've added more features, like path compression, some additional callbacks etc.

**Comment by aliasgarlabs** [comment]
@tmarzeion Thanks for the serialization feature! Is there any help needed in getting your fork merged into this one? I need this feature for my app too and I am happy to help! :)

**Comment by aliasgarlabs** [comment]
@tmarzeion I'm working on implementing your changes to this repository. I was having trouble understanding the following things

1. What is`lineToList` and what is it used for?
2. Can you please explain this [if condition](https://github.com/tmarzeion/painter/blob/e5106dbf2c44dffbc004284747e5be86c04575bc/lib/painter.dart#L245)? 


Thanks 🙂
